### ISSUE TITLE
[Bug]: Error Downloading File from OpenAI Assistant

### ISSUE THREAD

**Issue by awickham10** [danny-avila/LibreChat#9335]
### What happened?

We have LibreChat connecting to an OpenAI assistant, with code interpreter enabled. After upgrading to v0.8.0-rc3, if the OpenAI assistant uses code interpreter to generate a file ("Create me an Excel file with a list of the US states and their abbreviations"), when clicking the download file link it gets an error "Error downloading file . The file may have been deleted."

This does work on 0.7.7.

### Version Information

ghcr.io/danny-avila/librechat:v0.8.0-rc3

### Steps to Reproduce

1. Setup an OpenAI assistant with code interpreter enabled
2. Hookup LibreChat to the assistant
3. Prompt the assistant: Create me an Excel file with a list of the US states and their abbreviations
4. Click the download link

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
From the web console:

Error downloading file: No data found
GET https://myserver/api/files/download/6811dfb9be2bd30b00a93171/file-D6jAEancp2JVEpj7iM8Hvv 500 (Internal Server Error)


From the app logs:

debug: File download requested by user 6811dfb9be2bd30b00a93171: file-D6jAEancp2JVEpj7iM8Hvv
debug: Downloading file file-D6jAEancp2JVEpj7iM8Hvv from OpenAI
debug: File file-D6jAEancp2JVEpj7iM8Hvv downloaded from OpenAI
error: [DOWNLOAD ROUTE] Error downloading file: passThrough.body.pipe is not a function
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by arthurian** [comment]
Hi @awickham10! 

We encountered this same issue and have submitted a bug fix already here: #9200. If you have the ability to test out that bug fix as well and confirm it works for you, that might help to get this merged in sooner rather than later as we're very eager to get this resolved for our deployment.

**Comment by danny-avila** [comment]
Closed by https://github.com/danny-avila/LibreChat/pull/9200.
