### ISSUE TITLE
run-summarization.test.ts fails tsc --noEmit on dev: buildChildInputs output is not assignable to its own input

### ISSUE THREAD

**Issue by danny-avila** [danny-avila/LibreChat#15496]
## Summary

`packages/api/src/agents/__tests__/run-summarization.test.ts` fails `tsc --noEmit` on current `dev` (`6372cb08e`). The regression test added in #15492 feeds the result of `buildChildInputs` back into `buildChildInputs`, and the return type is looser than the parameter type.

```
src/agents/__tests__/run-summarization.test.ts(2078,7): error TS2345: Argument of type 'SubagentConfigEntry' is not assignable to parameter of type 'ResolvedSubagentConfig'.
  Type 'SubagentConfig' is not assignable to type 'ResolvedSubagentConfig'.
    Types of property 'agentInputs' are incompatible.
      Type 'AgentInputs | undefined' is not assignable to type 'AgentInputs'.
        Type 'undefined' is not assignable to type 'AgentInputs'.
src/agents/__tests__/run-summarization.test.ts(2083,7): error TS2345: ...
```

Reproduced against an unmodified copy of the upstream file, so this is not downstream-specific.

## Cause

In `prunes shared-agent cycles per traversal path without dropping valid edges`, the root configs are cast to the parameter type:

```ts
const rootConfigs = agents[0].subagentConfigs as Parameters<typeof buildChildInputs>[0][];
```

but the shared configs derived from the call's own output are not:

```ts
const leftShared = leftInputs.subagentConfigs?.[0];
const rightShared = rightInputs.subagentConfigs?.[0];
...
const leftSharedInputs = buildChildInputs(leftShared, 'agent_shared', leftInputs.maxSubagentDepth);
```

`buildChildInputs` returns entries typed with `agentInputs?: AgentInputs`, while its parameter requires `agentInputs: AgentInputs`. Round-tripping the output therefore does not type-check.

## Suggested fix

Either apply the same cast the root configs already use:

```ts
type ChildInput = Parameters<typeof buildChildInputs>[0];
const leftShared = leftInputs.subagentConfigs?.[0] as ChildInput | undefined;
const rightShared = rightInputs.subagentConfigs?.[0] as ChildInput | undefined;
```

or, if the round trip is meant to be supported, align the two types in `@librechat/agents` so the output of `buildChildInputs` is directly usable as its input. The second is the better fix if callers outside tests do this too; the cast only silences it at this call site.

## Note

Only the test file is affected — the runtime path is unaffected, and the test itself passes at runtime. But it does break `tsc --noEmit` for the whole `packages/api` project, so anything gating on that (including downstream forks running the same check) fails.
